### ISSUE TITLE
Consider implementing a way to postpone running benchmarks

### ISSUE THREAD

**Issue by aochagavia** [rustls/rustls-bench-app#23]
There are a few scenarios where it makes sense to postpone running benchmarks, to avoid competing for resources and prevent noise in the results:

1. When manually running other performance benchmarks (like in [this case](https://github.com/aochagavia/rustls-bench-results/tree/1827fe3ee0029827e2adc9561bbb7c7895c47102)).
2. When building and deploying a new version of the application (since the app is built on the server).

Currently, the only way to avoid running benchmarks in reaction to GitHub events is to shut down the application entirely. If we do so, however, GitHub events get lost, which is unfortunate. The current way to recover them is that someone goes to the rustls-benchmarking GitHub app's page and manually redelivers any relevant webhooks.

I'm tempted to leave this as wontfix, because I don't expect it will cause problems in practice. That way we avoid the extra complexity.

**Comment by cpu** [comment]
> My current idea is to associate a systemd socket with the service, so maintainers with SSH access can send commands to the service's stdin

That sounds reasonable if we were thinking there might be additional commands in the future. I think with this design we'd need ~2 commands at minimum: `pause [on/off]` and `status` to show what the pause toggle state is.

Alternatively, if this is likely to be the only administrative action we anticipate needing maybe we can get away with just using a canary file on disk in a well known location. Something like `/home/ci-bench-runner/pause`. If we `touch` that file, the system will be paused. If we `rm` it, the pause is removed.

**Comment by aochagavia** [comment]
I like the canary file alternative!

Regarding other possible commands, there is one that could be useful in the future: running the benchmarks for the current main branch, one or more times, and storing the results so they get picked up when deriving the significance thresholds. The only way to do this right now is by updating the main branch _or_ by spoofing a GitHub webhook for that event (that's what I did last time, POSTing 30 times to the server, to initialize the database).

On the other hand, the command I mention would almost never be necessary (and there is a reasonable workaround for it), so we should probably go with the canary file. Agree?
